#!/bin/bash

# Demo script for metrics - Performance metrics tracking action

set -e

echo "=========================================="
echo "  📊 Metrics - Performance Tracking"
echo "  GitHub Action for Workflow Analytics"
echo "=========================================="
echo ""

echo "🔍 Action Overview:"
if [ -f "package.json" ]; then
    echo "   ✅ Node.js action detected"
    echo "   Purpose: Track workflow performance metrics"
    echo "   Framework: TypeScript + Vercel"
else
    echo "   ⚠️  package.json not found"
fi

echo ""
echo "✨ Metrics Tracked:"
echo ""
echo "   ⏱️  Performance Metrics"
echo "      • Workflow execution time"
echo "      • Job duration tracking"
echo "      • Step-level timing"
echo "      • Resource utilization"
echo ""
echo "   📈 Analytics"
echo "      • Success/failure rates"
echo "      • Build trends over time"
echo "      • Performance regression detection"
echo "      • Historical data visualization"
echo ""
echo "   🔔 Alerting"
echo "      • Performance degradation alerts"
echo "      • Threshold breach notifications"
echo "      • Slack/email integration"
echo "      • Custom webhook support"
echo ""

echo "📝 Usage Example:"
echo ""
echo "   name: Track Metrics"
echo "   on: [push, pull_request]"
echo ""
echo "   jobs:"
echo "     metrics:"
echo "       runs-on: ubuntu-latest"
echo "       steps:"
echo "         - uses: actions/checkout@v3"
echo "         - uses: wesleyscholl/metrics@v1"
echo "           with:"
echo "             tracking-id: 'my-project'"
echo "             metrics: 'duration,success_rate,resource_usage'"
echo "             upload-results: true"
echo ""

echo "📊 Dashboard Features:"
echo ""
echo "   • Real-time metric visualization"
echo "   • Historical trend charts"
echo "   • Comparative analysis (branches, PRs)"
echo "   • Export to CSV/JSON"
echo "   • Embeddable badges"
echo ""

echo "🚀 Quick Start:"
echo ""
echo "   1. Add action to workflow"
echo "   2. Configure metric collection"
echo "   3. View dashboard at metrics.vercel.app"
echo "   4. Set alert thresholds"
echo "   5. Integrate with Slack/Discord"
echo ""

echo "💡 Use Cases:"
echo "   • CI/CD performance monitoring"
echo "   • Build time optimization"
echo "   • Resource cost tracking"
echo "   • Team productivity analysis"
echo "   • Deployment frequency metrics"
echo ""

echo "📈 Example Metrics Output:"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Workflow: CI Pipeline"
echo "   Duration: 3m 42s"
echo "   Success Rate: 94.3%"
echo "   Avg Resource: 512MB RAM, 2 CPUs"
echo "   Trend: ↑ 5% faster than last week"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "=========================================="
echo "  Repository: github.com/wesleyscholl/metrics"
echo "  Type: GitHub Action | Vercel Integration"
echo "=========================================="
echo ""
