query AchievementsDefault {

  user(login: "$login") {
    repositories(first: 100, privacy: PUBLIC, affiliations: OWNER, orderBy: {field: CREATED_AT, direction: ASC}) {
      nodes {
        createdAt
        nameWithOwner
        forkCount
        languages(first: 10) {
          edges {
            node {
              name
            }
          }
        }
      }
      totalCount
    }
    forks:repositories(first: 1, privacy: PUBLIC, isFork: true, orderBy: {field: CREATED_AT, direction: ASC}) {
      nodes {
        createdAt
        nameWithOwner
      }
      totalCount
    }
    popular:repositories(first:1, orderBy: {field: STARGAZERS, direction: DESC}) {
      nodes {
        stargazers {
          totalCount
        }
      }
    }
    pullRequests(orderBy: {field: CREATED_AT, direction: ASC}, first: 1) {
      nodes {
        createdAt
        title
        repository {
          nameWithOwner
        }
      }
      totalCount
    }
    contributionsCollection {
      pullRequestReviewContributions(first: 1, orderBy: {direction: ASC}) {
        nodes {
          occurredAt
          pullRequest {
            title
            number
            repository {
              nameWithOwner
            }
          }
        }
        totalCount
      }
    }
    projectsV2(first: 1, orderBy: {field: CREATED_AT, direction: ASC}) {
      totalCount
    }
    packages(first: 1, orderBy: {direction: ASC, field: CREATED_AT}) {
      totalCount
    }
    organizations(first: 1) {
      totalCount
    }
    gists(first: 1, orderBy: {field: CREATED_AT, direction: ASC}) {
      nodes {
        createdAt
        name
      }
      totalCount
    }
    starredRepositories {
      totalCount
    }
    followers {
      totalCount
    }
    following {
      totalCount
    }
    bio
    status {
      message
    }
    sponsorshipsAsSponsor {
      totalCount
    }
    discussionsStarted: repositoryDiscussions {
      totalCount
    }
    discussionsComments: repositoryDiscussionComments {
      totalCount
    }
    discussionAnswers: repositoryDiscussionComments(onlyAnswers: true) {
      totalCount
    }
  }
}